name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shalzz/zola-deploy-action@v0.15.3
        env:
          PAGES_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY: Shywim/shywim.github.io
